name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet pack "DickinsonBros.DateTime.Abstractions" -c Release  -p:PackageID="DickinsonBros.DateTime.Abstractions"
    - name: Publish Package
      run: dotnet nuget push ./DickinsonBros.DateTime.Abstractions/bin/Release/*.nupkg -k ${{ secrets.NugetKey }} -s https://api.nuget.org/v3/index.json

